console.log(address);
var address="Tanya";
let age;
console.log(age);
age=36;
console.log(age);
age=18;
console.log(age);
const hobby="music";
console.log(hobby);
// hobby="serf";
console.log(hobby);
